version: "3.8"

services:
  server:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    volumes:
      - ${SERVER_PATH}:/server
    restart: unless-stopped
    environment:
      - RESTART_CONTAINER_ON_STOP=${RESTART_CONTAINER_ON_STOP:-1}
      - RCON_ENABLED=${RCON_ENABLED:-1}
      - RCON_PORT=${RCON_PORT:-25575}
      - RCON_PASSWORD=${RCON_PASSWORD}
  rcon:
    image: itzg/rcon
    restart: unless-stopped
    ports:
      - "4326:4326"
      - "4327:4327"
    environment:
      - RWA_PASSWORD=${RWA_PASSWORD:?error}
      - RWA_RCON_HOST=server
      - RWA_RCON_PASSWORD=${RCON_PASSWORD}


