version: "3.8"

services:
  mc:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    volumes:
      - ${SERVER_PATH}:/server
    restart: unless-stopped
    environment:
      - RESTART_CONTAINER_ON_STOP=${RESTART_CONTAINER_ON_STOP:-1}
